### ISSUE TITLE
datebase_process.py error when car exiting carpark

### ISSUE THREAD

**Issue by vands2013** [softwarepyrate/LPC#12]
Error details:
Traceback (most recent call last):
  File "C:\Users\matth\AppData\Local\Programs\Python\Python39\lib\tkinter__init.py", line 1892, in call__
    return self.func(*args)
  File "C:\Users\matth\Documents\LPC\GUI2.py", line 99, in <lambda>
    command=lambda: exit_carpark())  # using Button
  File "C:\Users\matth\Documents\LPC\GUI2.py", line 85, in exit_carpark
    test_parking_fee = fee.fee_calculation(datebase_process.export_entry_datetime(numberplate_number), exit_datatime)
  File "C:\Users\matth\Documents\LPC\datebase_process.py", line 149, in export_entry_datetime
    created_date = datetime.strptime(new_string, '%Y-%m-%d %H:%M:%S')
  File "C:\Users\matth\AppData\Local\Programs\Python\Python39\lib_strptime.py", line 568, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
  File "C:\Users\matth\AppData\Local\Programs\Python\Python39\lib_strptime.py", line 349, in _strptime
    raise ValueError("time data %r does not match format %r" %
ValueError: time data 'ne' does not match format '%Y-%m-%d %H:%M:%S'

**Comment by vands2013** [comment]
Error caused by logical error, fixed at https://github.com/softwarepyrate/LPC/commit/831b52419e4cf175a8e812b320c72c83e90e686d.

Cheers
